# -*- coding: utf-8 -*-
"""calculadora01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NcLr8AB3tuH7f8XGyDDIOSE1hs0aBeyW

#Calculadora Loop
"""

print('Operações: +, -, *, /')
print('Digite sair para encerrar\n')

while True:
    num1 = input('Digite o primeiro numero: ')

    if num1 == 'sair':
        print('Encerrando...')
        break

    num2 = input('Digite o segundo numero: ')
    operaçãoo = input('Escolha a operação (+ - * /): ')

    num1_num = float(num1)
    num2_num = float(num2)

    if operacao == '+':
        resultado = num1_num + num2_num
        print(f'{num1_num} + {num2_num} = {resultado}')
    elif operacao == '-':
        resultado = num1_num - num2_num
        print(f'{num1_num} - {num2_num} = {resultado}')
    elif operacao == '*':
        resultado = num1_num * num2_num
        print(f'{num1_num} * {num2_num} = {resultado}')
    elif operacao == '/':
        resultado = num1_num / num2_num
        print(f'{num1_num} / {num2_num} = {resultado}')
    else:
        print('Operação inválida!')

    print('-' * 30)